name: Philosophers CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make gcc
      
    - name: Compile project
      run: |
        cd philo
        make re
        
    - name: Run basic tests
      run: |
        cd philo
        # Test 1: Verify program starts (controlled test)
        ./philo 4 800 200 200 > output.log 2>&1 &
        PID=$!
        sleep 3  # Let it run for 3 seconds
        
        if ps -p $PID > /dev/null; then
          echo "✅ Test 1 Passed (Program runs)"
          kill $PID
          wait $PID 2>/dev/null
        else
          echo "❌ Test 1 Failed (Program terminated early)"
          exit 1
        fi
        
        # Test 2: Meal limit
        ./philo 3 1000 200 200 5 > meals.txt
        grep -q "is eating" meals.txt || { echo "❌ Test 2 Failed"; exit 1; }
        echo "✅ Test 2 Passed (Meal limit works)"
        
        # Test 3: Single philosopher death
        ./philo 1 800 200 200 > single.txt
        grep -q "died" single.txt || { echo "❌ Test 3 Failed"; exit 1; }
        echo "✅ Test 3 Passed (Single philo dies)"